# Generated by Django 2.2.12 on 2024-06-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('maths_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('science_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hindi_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('english_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sanskrit_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
