# Generated by Django 2.2.12 on 2024-06-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AveragePercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
