# Generated by Django 2.2.12 on 2024-06-27 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_averagepercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='average_percentage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app.AveragePercentage'),
        ),
    ]
