# Generated by Django 2.2.12 on 2024-06-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_average_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='average_percentage',
        ),
    ]
